In [2]:
import numpy as np

#Create a numpy array
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [4]:
arr2=np.ones((3,4))
print(arr2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [5]:
arr3=np.eye(4)
print(arr3)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
#Numpy vectorized operation
arr1 = np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])
#Elementwise addition
print("Array: ", arr1+arr2)

Array:  [11 22 33 44 55]


In [11]:
#Universal functions
arr1 = np.array([[1,2,3,4,5],[-1,-2,-3,-4,-5]])
mean=np.mean(arr1)
std=np.std(arr1)
# Normalised data
norm_array = (arr1 - mean)/std
print("Normalized array:\n", norm_array)
print("Mean(Norm): ", np.mean(norm_array))
print("STD(Norm): ", np.std(norm_array))

Normalized array:
 [[ 0.30151134  0.60302269  0.90453403  1.20604538  1.50755672]
 [-0.30151134 -0.60302269 -0.90453403 -1.20604538 -1.50755672]]
Mean(Norm):  -2.2204460492503132e-17
STD(Norm):  1.0


In [16]:
# Array filtering
filter_arr1 = (arr1>=-2) & (arr1<=3)
print("Array filter: ", filter_arr1)
print("Filtered Array: ", arr1[filter_arr1])

Array filter:  [[ True  True  True False False]
 [ True  True False False False]]
Filtered Array:  [ 1  2  3 -1 -2]
